"""Add YJS document state table

Revision ID: 4267ccd5c861
Revises: 997d1165ec4e
Create Date: 2025-12-11 11:23:03.339150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4267ccd5c861'
down_revision: Union[str, None] = '997d1165ec4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yjs_document_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yjs_document_states_id'), 'yjs_document_states', ['id'], unique=False)
    op.create_index(op.f('ix_yjs_document_states_project_id'), 'yjs_document_states', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yjs_document_states_project_id'), table_name='yjs_document_states')
    op.drop_index(op.f('ix_yjs_document_states_id'), table_name='yjs_document_states')
    op.drop_table('yjs_document_states')
    # ### end Alembic commands ###
