"""Add YJS state persistence table

Revision ID: 997d1165ec4e
Revises: 9d17ab4c17a8
Create Date: 2025-12-11 10:51:24.035891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '997d1165ec4e'
down_revision: Union[str, None] = '9d17ab4c17a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
